services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    command: mongod --noauth 
    volumes:
      - mongodb_data:/data/db
    networks:
      - microtaller_network

  api:
    build: ./microtaller2
    container_name: go_api_container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: container-microtaller2
    networks:
      - microtaller_network

  logs_service:
    build: ./logs_service
    container_name: python_logs_service
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: logs_service
    networks:
      - microtaller_network

volumes:
  mongodb_data:

networks:
  microtaller_network:
    driver: bridge
